name: button_navigation_bar
description: A lightweight, customizable navigation bar widget for flutter which can be used as a FAB as well as a fixed Widget.
version: 0.1.1
repository: https://github.com/underwhelmingToaster/button_navigation_bar

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# flutter:
#  plugin:
#    platforms:
#      android:
#        package: com.example.button_navigation_bar
#        pluginClass: ButtonNavigationBar
#      ios:
#        pluginClass: ButtonNavigationBar
#      macos:
#        pluginClass: ButtonNavigationBar